### ISSUE TITLE
Floating point is not recommended here

### ISSUE THREAD

**Issue by daveythacher** [samyk/dingdong#2]
This is a bad usage of floating point, which is resource intensive for Arduino/AVR. Most of the logic can be reduced into integer math with precomputation. Also the single ring function can be collapsed a little which will limit overflows along with cleaner structure.

Perhaps the C++ compiler would catch this. However for such a simple program and how easy this is I see no point banking on that. This code is also a little cleaner and friendly to modifications or extensions to an extent.

While I understand this code is tested there is a number of potential timing delays that can exist in this program. Removing floating point is one, while the other is serial. Granted serial or random delays is in not critical sections, but the floating point delays could potentially exist in the critical path. In this case not likely to be significant.

#define BIT_PERIOD 7

int times[] = {
 0, 15, 30, 45,  92, 122, 161, 214,
 268, 298, 352, 413,  436, 505, 535, 574,
 620, 673, 719, 757,  803
};

void single_ring()
{
	for (int i = 0; i < sizeof(times) / sizeof(int); i++)
	{
		if (i > 0)
			delayMicroseconds((times[i] - times[i - 1] - BIT_PERIOD) * 100);
		digitalWrite(TX_PIN, HIGH);
		delayMicroseconds(BIT_PERIOD * 100);
		digitalWrite(TX_PIN, LOW);
	}
	delay(20);
}

I did try to create a branch and push the logic, but was locked out. So instead of pull request I created an issue.

**Comment by samyk** [comment]
Hi, I don't know why you were "locked out" but I'm happy to accept pull requests as you can see from previous commits.

As you noted, the "delays" are not "significant". The instructions are running at tens of nanoseconds while a single bit in the RF stream is in the milliseconds, tens of thousands of times longer. If you do manage to submit a PR, I'm happy to accept your suggested improvements.

**Comment by daveythacher** [comment]
At the time I did not know how Github pull request worked. Arduino does not use optimization by default, if I remember correctly. It targets space. 

It is a little more than that: https://forum.arduino.cc/t/math-execution-times-for-arduino/191501
Overall still nothing compared to 700. This probably tolerated, but may not be every time. I honestly have no clue.

I never realized just how bad this was. I knew it wasn't great but dang why would you compute on these. I guess I see why people who do this hate the PIC. Now I know why some people liked the PIC32 in the ChipKit, except Arduino who left it out in the cold. If you have decent FPU/32 bit ISA you would scream in comparison. I remember those days, only 10 years ago. Right before everything fell off a cliff. This was always a problem, but boy did it every make a hard turn for the rocks.

Anyhow these are MCUs they are great for many things. Optimized core or unoptimized, they not great computers and are still software based. You are supposed to use hardware to avoid doing IO in software. Be it peripheral, ISA, etc. Time is money though....assuming you know what your doing I guess that will work. Ah small wanna be tech companies such good times.

Not sure it matters here, but it could. In this case you are mostly building a state machine. This state machine never changes so you can precompute. If you write it properly the compiler, if enabled, may handle this for you. I may push a pull request, but I mostly want to just point this out in case it ever came up as an issue. Not likely but you never know.

**Comment by daveythacher** [comment]
I created a pull request. I am going to delete my fork here soon.

**Comment by samyk** [comment]
Grazie, merged
